encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = 'encyclo'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>/", views.wiki, name="entry"),
    path("new/", views.newPage, name="newpage"),
    path("new/<str:title>", views.newPage, name="newPageTitle"),
    path("edit/<str:entry>/", views.edit, name="edit"),
    path("random", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import re
import markdown2
from django.http import HttpResponse
from django.urls import reverse
from django.http import HttpResponseRedirect
import random

from . import util


def index(request):
    '''
    Check if request has a query parameter, if the parameter
    is an empty string the page is redirected to "index" path
    with no query parameters and then tha page is reloaded, if
    it's a non-empty string the request is redirected to "entry"
    path with the parameter as argument.
    '''
    if(request.GET):
        query = request.GET['q']
        if(re.search(r"\w", query)):
            return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': query}))
        else:
            return HttpResponseRedirect(reverse("encyclo:index"))

    # If there's no query parameters index is rendered
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request, entry):

    '''
    Requests with a query occurs when there's a search query from
    index or wiki pages.
    When there's a non-empty query the request will be redirected to "entry"
    path with the query as "entry" argument, resulting in "wiki/query/".
    If there's an empty string in the query it'll be redirect to "entry"
    path with entry as a parameter, resulting in a page reload.c
    '''
    if(request.GET):
        query = request.GET['q']

        if(query):
            return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': query}))
        else:
            return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': entry}))

    # Get the content for a given entry
    content = util.get_entry(entry)

    # If there's no matching entry, notFound is called to handle it
    if (content == None):
        return notFound(request, entry)

    # Else, render the page with its entry content
    else:
        print(entry)
        return render(request, "encyclopedia/wiki.html", {
            "title": entry + " - Wiki",
            "content": markdown2.markdown(content),
            "query": entry
    })

def notFound(request, entry):

        # Get all saved entries
        items = util.list_entries()

        '''
        If an item from util.list_entries() has entry as
        a sub string, that item is append to entries.
        '''
        entries = []

        for item in items:
            if re.search(entry, item, re.IGNORECASE):
                entries.append(item)

        '''
        Render a search result page with all matching entries or
        with a message informing that there's no similar page.
        '''
        return render(request, "encyclopedia/notfound.html", {
            "title": entry + " - Wiki",
            "query": entry,
            "entries": entries
        })

def newPage(request, title=""):

    if(request.method == "POST"):
        # Get all saved entries
        items = util.list_entries()

        title = request.POST["title"].strip()

        if(title in items):
            return HttpResponse("The page already exists.")
            
        content = request.POST["new-entry"]

        if(not re.search(r"\w", title) or not re.search(r"\w", content)):
            return error(request)

        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': title}))

    else:
        return render(request, "encyclopedia/newpage.html", {
            "title": title 
        })

def edit(request, entry):
    if(request.method == "POST"):
        content = request.POST["new-entry"]
        # Handle void input
        if (not re.search(r"\w", content)):
            return error(request)

        util.save_entry(entry, content)
        return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': entry}))

    content = util.get_entry(entry)
    return render(request, "encyclopedia/edit.html", {
        "content": content,
        "query": entry
    })

def randomPage(request):
    items = util.list_entries()
    entry = random.choice(items)
    return HttpResponseRedirect(reverse("encyclo:entry", kwargs={'entry': entry}))

def error(request):
    return render(request, "encyclopedia/error.html")

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit - {{ query }}
{% endblock %}

{% block body %}

<h1>Edit ~<em>{{ query }}</em>~</h1>

<form method="post">
  {% csrf_token %}
  <textarea name="new-entry" required>{{ content }}</textarea>
  <input class="submit-bt" type="submit" value="Save">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Invalid parameter
{% endblock %}

{% block body %}
<p>You used an invalid parameter in the form.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<div class="headings">
    <h1>All Pages</h1>
</div>


<ul>
    {% for entry in entries %}
    <li><a href="{% url 'encyclo:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/wikipedia_v2.ico' %}" />
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <!-- <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet"> -->
    <link href="{% static 'encyclopedia/index.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Original+Surfer&display=swap" rel="stylesheet">
    <script defer src="{% static 'encyclopedia/guide-button.js' %}"></script>
</head>

<body>
    <div class="myRow">
        <div class="sidebar" id="guide-content">
            <div class="guide">
                <button id="guide-button">
                    <svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false"
                        class="style-scope yt-icon"
                        style="pointer-events: none; display: block; width: 100%; height: 100%;">
                        <g class="style-scope yt-icon">
                            <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" class="style-scope yt-icon"></path>
                        </g>
                    </svg>
                </button>
            </div>
            <div class="logo"></div>
            <h2>
                <a href="{% url 'encyclo:index' %}">
                    Wiki
                </a>
            </h2>
            <form action="{% url 'encyclo:index' %}">
                <input type="text" name="q" placeholder="Search Encyclopedia" required>
            </form>
            <div class='home'>
                <a class='shift' href="{% url 'encyclo:index' %}">Home</a>
            </div>
            <div class='shift'>
                <a class='shift' href="{% url 'encyclo:newpage' %}">Create New Page</a>
            </div>
            <div class='shift'>
                <a class='shift' href="{% url 'encyclo:randomPage' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Page
{% endblock %}

{% block body %}

<h1>New page</h1>

<form method="post">
    {% csrf_token %}
    <p class="title-input">
        <label class="new-title" for="wefa">Title:</label>
        <input type="text" name="title" id="wefa" {% if title %} value="{{title}}" {% endif %} required>
    </p>
    <label class="new-title">Text:</label>
    <textarea name="new-entry" id="content" required></textarea>
    <input class="submit-bt" type="submit" value="Save">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
{% if entries %}
<h1 class='search-result'><em>"{{ query }}"</em> may refer to:</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'encyclo:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% else %}
<h5>The page <em>"{{ query }}"</em> does not exist.
    You can <a href="{% url 'encyclo:newPageTitle' query %}">ask for it to be created.</a>
</h5>
<p>There were no results matching the query.</p>
{% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}

{{ content|safe }}

<a href="{% url 'encyclo:edit' query %}">Edit</a>

{% endblock %}